sudo: required
dist: trusty

language: ruby

rvm:
  - 2.3.1

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - RAILS_ENV=test bin/rails db:create --trace
  - RAILS_ENV=test bin/rails db:migrate --trace

before_install:
  - gem install bundler && gem update bundler
  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

script:
  - bin/rails db:migrate --trace
  - bin/rails spec

cache:
  bundler: true
  directories:
    - vendor/bundle
    - node_modules
    - client/node_modules

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: $HEROKU_APP
  run:
    - rails db:migrate --trace