# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27208896cad720bd6296382a837d0a98f5c51c5c28bf36c69275b92281a69b836fac69be3adbb322b4b505b6b37dd466dde85004c232c016e86b9d7984e33bc1

test:
  secret_key_base: ae076945053eb567d595bc115c7c7f05eecb353ee43b58cf64fa3bd2cba1f3e1430d150df0280f5352f451630bbf78974f41d3b52b427ffef960069d11d1656b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
